import os
import anthropic

# ── CONFIG ───────────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "YOUR_ANTHROPIC_KEY_HERE")
MODEL = "claude-haiku-4-5-20251001"
MAX_TOKENS = 180  # Enough for 2-3 clear sentences

SYSTEM_PROMPT = """You are a child safety assistant helping parents understand online risks.
When given a message and its detected risk signals, explain in 2-3 plain sentences:
1. What specific behaviour or tactic the message shows
2. Why it could be dangerous for a child

Rules:
- Write for a worried, non-technical parent
- Be clear and direct, not alarmist
- Never reproduce the original message verbatim
- Never give legal advice
- If the message seems low risk despite the flag, say so honestly
- Keep your answer under 60 words"""


def explain_risk(msg: dict) -> str:
    """
    Takes a message dict (with grooming_stages, risk_score, escalation_flag etc.)
    and returns a plain-English explanation string.

    The explanation is generated by Claude Haiku and cached in the message dict
    under the key "risk_explanation".

    Usage:
        from explainer import explain_risk
        explanation = explain_risk(msg)
    """
    try:
        client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

        # Build a structured prompt with all available signals
        stages = msg.get("grooming_stages", {})
        stage_list = ", ".join(
            f"{k} (×{v})" for k, v in stages.items() if v > 0
        ) or "none detected"

        user_prompt = (
            f"Message: [redacted for privacy — classified by our system]\n"
            f"Risk score: {msg.get('risk_score', 0):.2f} / 1.00\n"
            f"Grooming stages detected: {stage_list}\n"
            f"Escalation flag: {'YES' if msg.get('escalation_flag') else 'no'}\n"
            f"Dominant emotion detected: {msg.get('emotion_label', 'unknown')}\n\n"
            f"Explain why this message was flagged."
        )

        response = client.messages.create(
            model=MODEL,
            max_tokens=MAX_TOKENS,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}]
        )

        explanation = response.content[0].text.strip()
        return explanation

    except Exception as e:
        print(f"[explainer] API error: {e}")
        return (
            "This message was flagged by our automated system based on "
            "risk patterns. Please review it manually."
        )


def enrich_message_explanation(msg: dict) -> dict:
    """
    Adds a 'risk_explanation' field to the message dict.
    Only calls the API if the message is actually risky (saves cost).

    Usage:
        from explainer import enrich_message_explanation
        msg = enrich_message_explanation(msg)
    """
    is_flagged = (
        msg.get("is_risky")
        or msg.get("is_grooming")
        or msg.get("escalation_flag")
        or msg.get("emotion_risky")
    )

    if is_flagged:
        msg["risk_explanation"] = explain_risk(msg)
    else:
        msg["risk_explanation"] = None

    return msg
